/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text.ui.contentassist

import org.yazgel.snow.notation.text.ui.contentassist.AbstractModuleProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ModuleProposalProvider extends AbstractModuleProposalProvider {
}
