/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ModuleStandaloneSetup extends ModuleStandaloneSetupGenerated{

	public static void doSetup() {
		new ModuleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

