/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ModuleRuntimeModule extends org.yazgel.snow.notation.text.AbstractModuleRuntimeModule {

}
