/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SnowStandaloneSetup extends SnowStandaloneSetupGenerated{

	public static void doSetup() {
		new SnowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

