/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.yazgel.snow.notation.text.services.ModuleGrammarAccess;

public class ModuleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ModuleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.yazgel.snow.notation.text.parser.antlr.internal.InternalModuleParser createParser(XtextTokenStream stream) {
		return new org.yazgel.snow.notation.text.parser.antlr.internal.InternalModuleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public ModuleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ModuleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
