/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ModuleAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/yazgel/snow/notation/text/parser/antlr/internal/InternalModule.tokens");
	}
}
