/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SnowUiModule extends org.yazgel.snow.notation.text.ui.AbstractSnowUiModule {
	public SnowUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
