/*
 * generated by Xtext
 */
package org.yazgel.snow.notation.text;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SnowUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.yazgel.snow.notation.text.ui.internal.SnowActivator.getInstance().getInjector("org.yazgel.snow.notation.text.Snow");
	}
	
}
